const std = @import("std");
const bpf = @import("bpf.zig");
const tc = @import("tc.zig");
const c = @import("c");
const mem = std.mem;
const Thread = std.Thread;

const print = std.debug.print;

var ready_ports: usize = 0;

var running: std.atomic.Value(bool) = std.atomic.Value(bool).init(true);

fn sigintHandler(sig: std.posix.SIG) callconv(.c) void {
    _ = sig;
    running.store(false, .monotonic);
}

/// Returns the cookie for the current network namespace (netns).
///
/// A cookie uniquely identifies a netns.
pub fn getCurrentNetNsCookie() !u64 {
    const sockfd: i32 = @intCast(std.os.linux.socket(
        std.os.linux.AF.INET,
        std.os.linux.SOCK.STREAM,
        0,
    ));
    if (sockfd < 0) {
        return std.posix.unexpectedErrno(std.posix.errno(sockfd));
    }

    var cookie: u64 = 0;
    var len: std.posix.socklen_t = @sizeOf(u64);

    const rc = std.os.linux.getsockopt(
        sockfd,
        std.posix.SOL.SOCKET,
        c.SO_NETNS_COOKIE,
        @ptrCast(&cookie),
        &len,
    );

    if (rc != 0) {
        return std.posix.unexpectedErrno(std.posix.errno(rc));
    }

    return cookie;
}

/// A connection associated with a monitored port.
/// Only tracks local connections.
const Endpoint = struct {
    /// The local port for client
    peer_port: u16,
    /// The client PID
    pid: u32,
};

const Port = struct {
    number: u16,
    netns_cookie: u64,
    state: union(enum) {
        /// a socket is bound to this port
        active: struct {
            socket_cookie: u64,
            pid: u32,
        },
        /// nothing is bound to this port
        inactive,
        /// unknown state
        /// example: the program just started, doesn't know if a socket
        /// is bound to this port or not.
        unknown,
    },
    /// Connections made to this port.
    connections: std.ArrayList(Endpoint),
};

const Context = struct {
    /// ports we're interested in
    ports: []Port,
    allocator: std.mem.Allocator,
};

pub fn main(init: std.process.Init) !void {
    // handle ctrl-c (SIGINT)
    var act = std.posix.Sigaction{
        .handler = .{ .handler = sigintHandler },
        .mask = std.posix.sigemptyset(),
        .flags = 0,
    };
    std.posix.sigaction(std.posix.SIG.INT, &act, null);

    const arena = init.arena.allocator();
    const gpa = init.gpa;
    const io = init.io;
    const args = try init.minimal.args.toSlice(arena);

    _ = gpa;

    // The ports you provide as arguments are the ports your local services
    // will bind to and listen for connections at. "jolt" will then monitor
    // incoming connections to your services and let delay or drop traffic for
    // any connection (or all connections).
    const node_args = args[1..];
    var ports = try arena.alloc(Port, node_args.len);
    for (node_args, 0..) |arg, i| {
        ports[i] = .{
            .number = try std.fmt.parseInt(u16, arg, 10),
            .state = .unknown,
            // only support current ns for now
            .netns_cookie = try getCurrentNetNsCookie(),
            .connections = .empty,
        };
    }

    try tc.init(io);
    defer tc.deinit(io) catch {};

    // This context object will be passed to ebpf hooks.
    // to be more specific, that will be passed to functions that handle new events
    // from eBPF ring buffer maps.
    var ctx: Context = .{
        .ports = ports,
        .allocator = arena,
    };

    var dummy: *bpf.Object(
        "prog.bpf.o",
        &.{
            "inet_bind_exit",
            "inet_listen_stop",
            "inet_csk_accept_exit",
            "tcp_v4_connect_exit",
        },
        &.{"events_buf"},
    ) = try .init(std.heap.c_allocator);
    defer dummy.deinit(std.heap.c_allocator);

    try dummy.attach();

    var rb: bpf.RingBuffer = try .init(dummy.maps.events_buf, handle_event, @ptrCast(&ctx));

    print("waiting for ports\n", .{});
    while (running.load(.monotonic)) {
        _ = try rb.poll_once(.fromSeconds(1));
    }
    print("done\n", .{});
}

/// Handle events generated by the eBPF programs.
///
/// `handle_event` is called by libbpf when a new ring buffer entry is pushed
/// from eBPF.
fn handle_event(_ctx: ?*anyopaque, data: ?*anyopaque, size: usize) callconv(.c) c_int {
    _ = size;

    const ctx: *Context = @ptrCast(@alignCast(_ctx.?));
    const event: *const c.jolt_event = @ptrCast(@alignCast(data.?));

    switch (event.tag) {
        c.EVENT_BIND, c.EVENT_RELEASE => {
            const socket = event.data.socket;
            const is_bind = event.tag == c.EVENT_BIND;

            print("{d}/{d} - {d} {s}\n", .{
                socket.ns_cookie,
                socket.cookie,
                socket.port,
                if (is_bind) "bound" else "closed",
            });

            for (ctx.ports) |*port| {
                if (port.netns_cookie == socket.ns_cookie and port.number == socket.port) {
                    if (is_bind) {
                        port.state = .{ .active = .{ .socket_cookie = socket.cookie, .pid = event.pid } };
                    } else {
                        port.state = .inactive;
                        port.connections.clearRetainingCapacity();
                    }
                }
            }
        },
        c.EVENT_ACCEPT => {
            const accept = event.data.accept;
            print("accept on port {d}: new connection from client port {d} (pid={d})\n", .{
                accept.listening.port,
                accept.peer_port,
                accept.client_pid,
            });

            for (ctx.ports) |*port| {
                if (port.netns_cookie == accept.listening.ns_cookie and
                    port.number == accept.listening.port)
                {
                    port.connections.append(ctx.allocator, .{
                        .peer_port = accept.peer_port,
                        .pid = accept.client_pid,
                    }) catch {};
                    print("port {d} has {d} connections\n", .{
                        port.number,
                        port.connections.items.len,
                    });
                }
            }
        },
        else => unreachable,
    }

    return 0;
}
